//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceTable
    {
        public int PriceID { get; set; }
        public System.DateTime PriceDate { get; set; }
        public decimal Price { get; set; }
    }
}
